"""Kakva mi beshe parolata

Revision ID: 04dd2f140cba
Revises: cb4cf10bf6a7
Create Date: 2024-10-05 14:58:29.877819

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '04dd2f140cba'
down_revision = 'cb4cf10bf6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'result', 'topic', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.drop_column('result', 'topic_id')
    # ### end Alembic commands ###
