"""Fix link

Revision ID: cb4cf10bf6a7
Revises: 942d7d2bbdf6
Create Date: 2024-10-05 14:52:18.691625

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cb4cf10bf6a7'
down_revision = '942d7d2bbdf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'question', 'topic', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'topic_id')
    # ### end Alembic commands ###
